# code_generator/stage_5_deployer.py

import os
import shutil
import subprocess
import sys
from datetime import datetime
from typing import Dict, Optional

class Stage5Deployer:
    """
    Stage 5: Deploys a tested agent
    - Saves final version
    - Makes it executable (Unix) or provides run command (Windows)
    - Optionally creates a simple API wrapper
    - Returns run instructions
    """

    def __init__(self, deploy_dir: str = "deployed_agents"):
        self.deploy_dir = deploy_dir
        os.makedirs(self.deploy_dir, exist_ok=True)

    def deploy(self, tested_file: str, agent_name: Optional[str] = None,
               create_api: bool = False, api_port: int = 8000) -> Dict:
        """
        Deploy the agent.

        Args:
            tested_file: Path to the tested agent .py file (output of Stage 4)
            agent_name: Friendly name for the agent (default: derived from filename)
            create_api: If True, generate a FastAPI wrapper
            api_port: Port for API server (if create_api)

        Returns:
            Dict with deployment info, commands, and status
        """
        if not os.path.exists(tested_file):
            return {
                "success": False,
                "error": f"File not found: {tested_file}"
            }

        # Generate a clean agent name
        if not agent_name:
            base = os.path.basename(tested_file).replace(".py", "")
            agent_name = base.replace("_agent", "").replace("_", " ").title()

        # Destination file in deploy directory
        dest_filename = f"{agent_name.lower().replace(' ', '_')}_deployed.py"
        dest_path = os.path.join(self.deploy_dir, dest_filename)

        # Copy the tested agent to deploy directory
        shutil.copy2(tested_file, dest_path)
        self._make_executable(dest_path)  # does nothing on Windows

        # Basic run command
        run_cmd = f"python {dest_path}"
        run_instruction = f"▶️  Run the agent:\n   {run_cmd}"

        # Prepare result
        result = {
            "success": True,
            "agent_name": agent_name,
            "source_file": tested_file,
            "deployed_file": dest_path,
            "run_command": run_cmd,
            "run_instruction": run_instruction,
            "import_path": dest_path.replace(".py", "").replace(os.sep, "."),
            "timestamp": datetime.now().isoformat(),
            "api_info": None
        }

        # Optional API wrapper
        if create_api:
            api_info = self._create_api_wrapper(agent_name, dest_path, api_port)
            result["api_info"] = api_info
            result["run_instruction"] += f"\n\n🌐 Or start API server:\n   {api_info['start_command']}\n   Then POST to http://localhost:{api_port}/ask"

        return result

    def _make_executable(self, filepath: str):
        """Make file executable on Unix (ignored on Windows)."""
        if sys.platform != "win32":
            try:
                os.chmod(filepath, 0o755)
            except Exception:
                pass

    def _create_api_wrapper(self, agent_name: str, agent_file: str, port: int) -> Dict:
        """Generate a FastAPI wrapper for the agent."""
        wrapper_filename = f"{agent_name.lower().replace(' ', '_')}_api.py"
        wrapper_path = os.path.join(self.deploy_dir, wrapper_filename)

        # Simplified import path: just the module name (file name without .py)
        # This avoids path traversal issues; the API wrapper will run in the same directory
        agent_module_name = os.path.basename(agent_file).replace(".py", "")
        # No directory prefix needed – the wrapper will be in the same folder as the agent file
        # or we rely on Python's path resolution.

        api_code = f'''"""
FastAPI wrapper for {agent_name}
Auto‑generated by Meta‑Agent Stage 5
"""

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from {agent_module_name} import Agent
import uvicorn

app = FastAPI(title="{agent_name} API", description="Auto‑deployed agent")

agent = Agent()

class Query(BaseModel):
    text: str

@app.post("/ask")
async def ask(query: Query):
    try:
        response = agent.run(query.text)
        return {{"answer": response}}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/health")
async def health():
    return {{"status": "healthy", "agent": "{agent_name}"}}

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port={port})
'''
        with open(wrapper_path, "w", encoding="utf-8") as f:
            f.write(api_code)

        return {
            "wrapper_file": wrapper_path,
            "start_command": f"python {wrapper_path}",
            "port": port,
            "endpoint": f"http://localhost:{port}/ask",
            "example_curl": f'curl -X POST http://localhost:{port}/ask -H "Content-Type: application/json" -d \'{{"text": "What is AI?"}}\''
        }

    @staticmethod
    def quick_test(deployment_result: Dict) -> Dict:
        """Run a quick test of the deployed agent (optional, for demo)."""
        if not deployment_result.get("success"):
            return {"success": False, "error": "Deployment not successful"}
        run_cmd = deployment_result["run_command"]
        try:
            # Run with a test input via subprocess (non‑interactive)
            proc = subprocess.run(
                [sys.executable, "-c", f"import sys; sys.path.insert(0, '.'); from {deployment_result['import_path']} import Agent; a=Agent(); print(a.run('test'))"],
                capture_output=True, text=True, timeout=5
            )
            if proc.returncode == 0:
                return {"success": True, "test_output": proc.stdout.strip()}
            else:
                return {"success": False, "error": proc.stderr.strip()}
        except Exception as e:
            return {"success": False, "error": str(e)}


# Quick test for the deployer itself (requires Stage 4 output)
if __name__ == "__main__":
    # Example: assuming we have a tested agent file
    print("🚀 Stage 5 Deployer - Self Test")
    print("   (Create a dummy tested agent first)")

    dummy_agent = '''class Agent:
    def run(self, user_input: str) -> str:
        return f"Echo: {user_input}"
'''
    test_file = "generated_agents/test_agent.py"
    os.makedirs("generated_agents", exist_ok=True)
    with open(test_file, "w") as f:
        f.write(dummy_agent)

    deployer = Stage5Deployer()
    result = deployer.deploy(test_file, agent_name="EchoBot", create_api=True, api_port=8001)

    print("\n✅ Deployment result:")
    for key, val in result.items():
        if key not in ("run_instruction",):
            print(f"   {key}: {val}")

    # Quick test
    test = deployer.quick_test(result)
    print(f"\n🧪 Quick test: {test}")

    # Cleanup dummy
    # os.remove(test_file)  # optional